package khanzahmsanjungan;

import fungsi.sekuel;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class DlgCekKunjunganPertamaSEP extends javax.swing.JDialog {
    private final sekuel query = new sekuel();
    private final DlgRegistrasiSEPPertama form = new DlgRegistrasiSEPPertama(null, false);

    public DlgCekKunjunganPertamaSEP(java.awt.Frame parent, boolean id) {
        super(parent, id);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        PanelWall = new usu.widget.glass.PanelGlass();
        jPanel1 = new component.Panel();
        input = new component.TextBox();
        jLabel28 = new component.Label();
        batal = new widget.ButtonBig();
        konfirm = new widget.ButtonBig();
        jPanel3 = new javax.swing.JPanel();
        keypad8 = new javax.swing.JButton();
        keypad7 = new javax.swing.JButton();
        keypad9 = new javax.swing.JButton();
        keypad4 = new javax.swing.JButton();
        keypad5 = new javax.swing.JButton();
        keypad6 = new javax.swing.JButton();
        keypad2 = new javax.swing.JButton();
        keypad1 = new javax.swing.JButton();
        keypad3 = new javax.swing.JButton();
        keypad0 = new javax.swing.JButton();
        keypadBackspace = new javax.swing.JButton();
        keypadClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(1, 1));

        jPanel2.setBackground(new java.awt.Color(238, 238, 255));
        jPanel2.setForeground(new java.awt.Color(238, 238, 255));

        PanelWall.setBackground(new java.awt.Color(238, 238, 255));
        PanelWall.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/bpjs-amiz.png"))); // NOI18N
        PanelWall.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        PanelWall.setForeground(new java.awt.Color(238, 238, 255));
        PanelWall.setPreferredSize(new java.awt.Dimension(500, 150));
        PanelWall.setRound(false);
        PanelWall.setWarna(new java.awt.Color(238, 238, 255));

        javax.swing.GroupLayout PanelWallLayout = new javax.swing.GroupLayout(PanelWall);
        PanelWall.setLayout(PanelWallLayout);
        PanelWallLayout.setHorizontalGroup(
            PanelWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        PanelWallLayout.setVerticalGroup(
            PanelWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel2.add(PanelWall);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(238, 238, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 215, 255)), "::[ Cek Data Pasien!!! ]::", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Inter", 0, 30), new java.awt.Color(0, 131, 62))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 131, 62));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 70));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        input.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 131, 62), 2, true));
        input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input.setFont(new java.awt.Font("Inter", 0, 36)); // NOI18N
        input.setPreferredSize(new java.awt.Dimension(350, 75));
        input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(input, gridBagConstraints);

        jLabel28.setForeground(new java.awt.Color(0, 131, 62));
        jLabel28.setText("No. RM / No. Kartu BPJS : ");
        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel28.setPreferredSize(new java.awt.Dimension(450, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.ipady = 5;
        jPanel1.add(jLabel28, gridBagConstraints);

        batal.setBackground(new java.awt.Color(255, 255, 255));
        batal.setForeground(new java.awt.Color(51, 51, 51));
        batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        batal.setMnemonic('U');
        batal.setToolTipText("Alt+U");
        batal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        batal.setHorizontalTextPosition(javax.swing.SwingConstants.TRAILING);
        batal.setIconTextGap(2);
        batal.setMargin(new java.awt.Insets(0, 0, 0, 0));
        batal.setPreferredSize(new java.awt.Dimension(100, 75));
        batal.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        jPanel1.add(batal, gridBagConstraints);

        konfirm.setBackground(new java.awt.Color(255, 255, 255));
        konfirm.setForeground(new java.awt.Color(51, 51, 51));
        konfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/konfirmasi.png"))); // NOI18N
        konfirm.setMnemonic('U');
        konfirm.setToolTipText("Alt+U");
        konfirm.setFont(new java.awt.Font("Inter", 1, 11)); // NOI18N
        konfirm.setIconTextGap(0);
        konfirm.setMargin(new java.awt.Insets(0, 0, 0, 0));
        konfirm.setPreferredSize(new java.awt.Dimension(100, 75));
        konfirm.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        konfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirmActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        jPanel1.add(konfirm, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(238, 238, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(294, 402));

        keypad8.setFont(new java.awt.Font("Segoe UI SemiBold", 0, 48)); // NOI18N
        keypad8.setText("8");
        keypad8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keypad8ActionPerformed(evt);
            }
        });

        keypad7.setFont(new java.awt.Font("Segoe UI SemiBold", 0, 48)); // NOI18N
        keypad7.setText("7");
        keypad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keypad7ActionPerformed(evt);
            }
        });

        keypad9.setFont(new java.awt.Font("Segoe UI SemiBold", 0, 48)); // NOI18N
        keypad9.setText("9");
        keypad9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keypad9ActionPerformed(evt);
            }
        });

        keypad4.setFont(new java.awt.Font("Segoe UI SemiBold", 0, 48)); // NOI18N
        keypad4.setText("4");
        keypad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keypad4ActionPerformed(evt);
            }
        });

        keypad5.setFont(new java.awt.Font("Segoe UI SemiBold", 0, 48)); // NOI18N
        keypad5.setText("5");
        keypad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keypad5ActionPerformed(evt);
            }
        });

        keypad6.setFont(new java.awt.Font("Segoe UI SemiBold", 0, 48)); // NOI18N
        keypad6.setText("6");
        keypad6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keypad6ActionPerformed(evt);
            }
        });

        keypad2.setFont(new java.awt.Font("Segoe UI SemiBold", 0, 48)); // NOI18N
        keypad2.setText("2");
        keypad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keypad2ActionPerformed(evt);
            }
        });

        keypad1.setFont(new java.awt.Font("Segoe UI SemiBold", 0, 48)); // NOI18N
        keypad1.setText("1");
        keypad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keypad1ActionPerformed(evt);
            }
        });

        keypad3.setFont(new java.awt.Font("Segoe UI SemiBold", 0, 48)); // NOI18N
        keypad3.setText("3");
        keypad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keypad3ActionPerformed(evt);
            }
        });

        keypad0.setFont(new java.awt.Font("Segoe UI SemiBold", 0, 48)); // NOI18N
        keypad0.setText("0");
        keypad0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keypad0ActionPerformed(evt);
            }
        });

        keypadBackspace.setFont(new java.awt.Font("Segoe UI SemiBold", 0, 36)); // NOI18N
        keypadBackspace.setText("<-");
        keypadBackspace.setToolTipText("");
        keypadBackspace.setMaximumSize(new java.awt.Dimension(75, 75));
        keypadBackspace.setMinimumSize(new java.awt.Dimension(75, 75));
        keypadBackspace.setPreferredSize(new java.awt.Dimension(75, 75));
        keypadBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keypadBackspaceActionPerformed(evt);
            }
        });

        keypadClear.setFont(new java.awt.Font("Segoe UI SemiBold", 0, 48)); // NOI18N
        keypadClear.setText("C");
        keypadClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keypadClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(keypad4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(keypad5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(keypad6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(keypad1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(keypad2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(keypad3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(keypadClear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(keypad0, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(keypadBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(keypad7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(keypad8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(keypad9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keypad7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keypad8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keypad9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keypad4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keypad5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keypad6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keypad3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keypad2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keypad1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keypad0, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keypadBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keypadClear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jPanel3, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            if (input.getText().isBlank()) {
                JOptionPane.showMessageDialog(rootPane, "Isian masih kosong..!!");
                this.setCursor(Cursor.getDefaultCursor());
                return;
            }

            if ((query.cariIntegerSmc("select count(*) from referensi_mobilejkn_bpjs where norm = ? and tanggalperiksa = current_date()", input.getText()) > 0)
                || (query.cariIntegerSmc("select count(*) from referensi_mobilejkn_bpjs where nomorkartu = ? and tanggalperiksa = current_date()", input.getText()) > 0)) {
                JOptionPane.showMessageDialog(rootPane, "Pasien telah menggunakan Mobile JKN. Silahkan masuk melalui menu \"Cek In MobileJKN\"..!!");
                this.setCursor(Cursor.getDefaultCursor());
                return;
            }

            if (query.cariIntegerSmc("select count(*) from pasien where no_peserta = ?", input.getText()) == 1) {
                form.tampilKunjunganPertama(input.getText());
                form.setSize(this.getWidth(), this.getHeight());
                form.setLocationRelativeTo(jPanel1);
                form.setVisible(true);
                this.dispose();
            } else if (query.cariIntegerSmc("select count(*) from pasien where no_rkm_medis = ?", input.getText()) == 1) {
                form.tampilKunjunganPertama(query.cariIsiSmc("select no_peserta from pasien where no_rkm_medis = ?", input.getText()));
                form.setSize(this.getWidth(), this.getHeight());
                form.setLocationRelativeTo(jPanel1);
                form.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Data pasien tidak ditemukan!");
            }
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_inputKeyPressed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        dispose();
    }//GEN-LAST:event_batalActionPerformed

    private void konfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirmActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if (input.getText().isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Isian masih kosong..!!");
            this.setCursor(Cursor.getDefaultCursor());
            return;
        }

        if ((query.cariIntegerSmc("select count(*) from referensi_mobilejkn_bpjs where norm = ? and tanggalperiksa = current_date()", input.getText()) > 0)
            || (query.cariIntegerSmc("select count(*) from referensi_mobilejkn_bpjs where nomorkartu = ? and tanggalperiksa = current_date()", input.getText()) > 0)) {
            JOptionPane.showMessageDialog(rootPane, "Pasien telah menggunakan Mobile JKN. Silahkan masuk melalui menu \"Cek In MobileJKN\"..!!");
            this.setCursor(Cursor.getDefaultCursor());
            return;
        }

        if (query.cariIntegerSmc("select count(*) from pasien where no_peserta = ?", input.getText()) == 1) {
            form.tampilKunjunganPertama(input.getText());
            form.setSize(this.getWidth(), this.getHeight());
            form.setLocationRelativeTo(jPanel1);
            form.setVisible(true);
            this.dispose();
        } else if (query.cariIntegerSmc("select count(*) from pasien where no_rkm_medis = ?", input.getText()) == 1) {
            form.tampilKunjunganPertama(query.cariIsiSmc("select no_peserta from pasien where no_rkm_medis = ?", input.getText()));
            form.setSize(this.getWidth(), this.getHeight());
            form.setLocationRelativeTo(jPanel1);
            form.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Data pasien tidak ditemukan!");
        }
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_konfirmActionPerformed

    private void keypad8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_keypad8ActionPerformed
    {//GEN-HEADEREND:event_keypad8ActionPerformed
        input.setText(input.getText() + "8");
    }//GEN-LAST:event_keypad8ActionPerformed

    private void keypad7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_keypad7ActionPerformed
    {//GEN-HEADEREND:event_keypad7ActionPerformed
        input.setText(input.getText() + "7");
    }//GEN-LAST:event_keypad7ActionPerformed

    private void keypad9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_keypad9ActionPerformed
    {//GEN-HEADEREND:event_keypad9ActionPerformed
        input.setText(input.getText() + "9");
    }//GEN-LAST:event_keypad9ActionPerformed

    private void keypad4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_keypad4ActionPerformed
    {//GEN-HEADEREND:event_keypad4ActionPerformed
        input.setText(input.getText() + "4");
    }//GEN-LAST:event_keypad4ActionPerformed

    private void keypad5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_keypad5ActionPerformed
    {//GEN-HEADEREND:event_keypad5ActionPerformed
        input.setText(input.getText() + "5");
    }//GEN-LAST:event_keypad5ActionPerformed

    private void keypad6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_keypad6ActionPerformed
    {//GEN-HEADEREND:event_keypad6ActionPerformed
        input.setText(input.getText() + "6");
    }//GEN-LAST:event_keypad6ActionPerformed

    private void keypad2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_keypad2ActionPerformed
    {//GEN-HEADEREND:event_keypad2ActionPerformed
        input.setText(input.getText() + "2");
    }//GEN-LAST:event_keypad2ActionPerformed

    private void keypad1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_keypad1ActionPerformed
    {//GEN-HEADEREND:event_keypad1ActionPerformed
        input.setText(input.getText() + "1");
    }//GEN-LAST:event_keypad1ActionPerformed

    private void keypad3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_keypad3ActionPerformed
    {//GEN-HEADEREND:event_keypad3ActionPerformed
        input.setText(input.getText() + "3");
    }//GEN-LAST:event_keypad3ActionPerformed

    private void keypad0ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_keypad0ActionPerformed
    {//GEN-HEADEREND:event_keypad0ActionPerformed
        input.setText(input.getText() + "0");
    }//GEN-LAST:event_keypad0ActionPerformed

    private void keypadBackspaceActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_keypadBackspaceActionPerformed
    {//GEN-HEADEREND:event_keypadBackspaceActionPerformed
        if (input.getText().length() > 0) {
            StringBuilder backspace = new StringBuilder(input.getText());
            backspace.deleteCharAt(input.getText().length() - 1);
            input.setText(backspace.toString());
        }
    }//GEN-LAST:event_keypadBackspaceActionPerformed

    private void keypadClearActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_keypadClearActionPerformed
    {//GEN-HEADEREND:event_keypadClearActionPerformed
        input.setText("");
    }//GEN-LAST:event_keypadClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgCekKunjunganPertamaSEP dialog = new DlgCekKunjunganPertamaSEP(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.glass.PanelGlass PanelWall;
    private widget.ButtonBig batal;
    private component.TextBox input;
    private component.Label jLabel28;
    private component.Panel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton keypad0;
    private javax.swing.JButton keypad1;
    private javax.swing.JButton keypad2;
    private javax.swing.JButton keypad3;
    private javax.swing.JButton keypad4;
    private javax.swing.JButton keypad5;
    private javax.swing.JButton keypad6;
    private javax.swing.JButton keypad7;
    private javax.swing.JButton keypad8;
    private javax.swing.JButton keypad9;
    private javax.swing.JButton keypadBackspace;
    private javax.swing.JButton keypadClear;
    private widget.ButtonBig konfirm;
    // End of variables declaration//GEN-END:variables
    public void clearText() {
        input.setText("");
    }
}
