package khanzahmsanjungan;

public class DlgPengaturanAPM extends javax.swing.JDialog {
    public DlgPengaturanAPM(java.awt.Frame parent, boolean id) {
        super(parent, id);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new component.Panel();
        jPanel2 = new component.Panel();
        namaPrinterRegistrasi = new widget.TextBox();
        jLabel23 = new widget.Label();
        usernameFP = new widget.TextBox();
        jLabel8 = new widget.Label();
        namaPrinterBarcode = new widget.TextBox();
        jLabel24 = new widget.Label();
        passwordFP = new widget.TextBox();
        jLabel12 = new widget.Label();
        pathAplikasiFP = new widget.TextBox();
        jLabel26 = new widget.Label();
        pilihPrinterBarcode = new widget.Button();
        pilihPrinterRegistrasi = new widget.Button();
        cariAplikasiFP = new widget.Button();
        jPanel3 = new javax.swing.JPanel();
        simpan = new component.Button();
        batal = new component.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(1, 1));

        jPanel1.setBackground(new java.awt.Color(238, 238, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 238, 255), 1, true), "::[ Pengaturan APM ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Inter", 0, 12), new java.awt.Color(0, 131, 62))); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(543, 106));
        jPanel1.setPreferredSize(new java.awt.Dimension(543, 106));
        jPanel1.setLayout(new java.awt.BorderLayout(0, 1));

        jPanel2.setBackground(new java.awt.Color(238, 238, 255));
        jPanel2.setForeground(new java.awt.Color(0, 131, 62));
        jPanel2.setPreferredSize(new java.awt.Dimension(390, 120));
        jPanel2.setLayout(null);

        namaPrinterRegistrasi.setHighlighter(null);
        jPanel2.add(namaPrinterRegistrasi);
        namaPrinterRegistrasi.setBounds(230, 10, 340, 30);

        jLabel23.setForeground(new java.awt.Color(0, 131, 62));
        jLabel23.setText("Lokasi Aplikasi Fingerprint BPJS :");
        jLabel23.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel23.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel23);
        jLabel23.setBounds(25, 70, 200, 30);

        usernameFP.setBackground(new java.awt.Color(255, 255, 255));
        usernameFP.setHighlighter(null);
        jPanel2.add(usernameFP);
        usernameFP.setBounds(230, 100, 340, 30);

        jLabel8.setForeground(new java.awt.Color(0, 131, 62));
        jLabel8.setText("Printer Registrasi / SEP :");
        jLabel8.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel8);
        jLabel8.setBounds(25, 10, 200, 30);

        namaPrinterBarcode.setBackground(new java.awt.Color(255, 255, 255));
        namaPrinterBarcode.setHighlighter(null);
        jPanel2.add(namaPrinterBarcode);
        namaPrinterBarcode.setBounds(230, 40, 340, 30);

        jLabel24.setForeground(new java.awt.Color(0, 131, 62));
        jLabel24.setText("Password FP BPJS :");
        jLabel24.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel24.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel24);
        jLabel24.setBounds(25, 130, 200, 30);

        passwordFP.setBackground(new java.awt.Color(255, 255, 255));
        passwordFP.setHighlighter(null);
        jPanel2.add(passwordFP);
        passwordFP.setBounds(230, 130, 340, 30);

        jLabel12.setForeground(new java.awt.Color(0, 131, 62));
        jLabel12.setText("Printer Barcode :");
        jLabel12.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel12.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel12);
        jLabel12.setBounds(25, 40, 200, 30);

        pathAplikasiFP.setBackground(new java.awt.Color(255, 255, 255));
        pathAplikasiFP.setHighlighter(null);
        jPanel2.add(pathAplikasiFP);
        pathAplikasiFP.setBounds(230, 70, 340, 30);

        jLabel26.setForeground(new java.awt.Color(0, 131, 62));
        jLabel26.setText("Username FP BPJS :");
        jLabel26.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel26.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel26);
        jLabel26.setBounds(25, 100, 200, 30);

        pilihPrinterBarcode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/pilih.png"))); // NOI18N
        pilihPrinterBarcode.setMnemonic('X');
        pilihPrinterBarcode.setToolTipText("Alt+X");
        pilihPrinterBarcode.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        pilihPrinterBarcode.setGlassColor(new java.awt.Color(238, 238, 255));
        jPanel2.add(pilihPrinterBarcode);
        pilihPrinterBarcode.setBounds(570, 40, 40, 30);

        pilihPrinterRegistrasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/pilih.png"))); // NOI18N
        pilihPrinterRegistrasi.setMnemonic('X');
        pilihPrinterRegistrasi.setToolTipText("Alt+X");
        pilihPrinterRegistrasi.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        pilihPrinterRegistrasi.setGlassColor(new java.awt.Color(238, 238, 255));
        jPanel2.add(pilihPrinterRegistrasi);
        pilihPrinterRegistrasi.setBounds(570, 10, 40, 30);

        cariAplikasiFP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/pilih.png"))); // NOI18N
        cariAplikasiFP.setMnemonic('X');
        cariAplikasiFP.setToolTipText("Alt+X");
        cariAplikasiFP.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        cariAplikasiFP.setGlassColor(new java.awt.Color(238, 238, 255));
        jPanel2.add(cariAplikasiFP);
        cariAplikasiFP.setBounds(570, 70, 40, 30);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(238, 238, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(533, 120));
        jPanel3.setPreferredSize(new java.awt.Dimension(533, 120));

        simpan.setForeground(new java.awt.Color(0, 131, 62));
        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/konfirmasi.png"))); // NOI18N
        simpan.setMnemonic('S');
        simpan.setText("Simpan");
        simpan.setToolTipText("Alt+S");
        simpan.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        simpan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        simpan.setPreferredSize(new java.awt.Dimension(300, 45));
        jPanel3.add(simpan);

        batal.setForeground(new java.awt.Color(0, 131, 62));
        batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/reset.png"))); // NOI18N
        batal.setMnemonic('K');
        batal.setText("Batal");
        batal.setToolTipText("Alt+K");
        batal.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        batal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        batal.setPreferredSize(new java.awt.Dimension(300, 45));
        jPanel3.add(batal);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgPengaturanAPM dialog = new DlgPengaturanAPM(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.Button batal;
    private widget.Button cariAplikasiFP;
    private widget.Label jLabel12;
    private widget.Label jLabel23;
    private widget.Label jLabel24;
    private widget.Label jLabel26;
    private widget.Label jLabel8;
    private component.Panel jPanel1;
    private component.Panel jPanel2;
    private javax.swing.JPanel jPanel3;
    private widget.TextBox namaPrinterBarcode;
    private widget.TextBox namaPrinterRegistrasi;
    private widget.TextBox passwordFP;
    private widget.TextBox pathAplikasiFP;
    private widget.Button pilihPrinterBarcode;
    private widget.Button pilihPrinterRegistrasi;
    private component.Button simpan;
    private widget.TextBox usernameFP;
    // End of variables declaration//GEN-END:variables
}
