package khanzahmsanjungan;

import bridging.ApiBPJS;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.sql.Connection;
import java.util.Date;
import javax.swing.JOptionPane;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;

public class DlgSMCRegistrasiSEPOnsite extends javax.swing.JDialog {
    private final Connection koneksi = koneksiDB.condb();
    private final sekuel query = new sekuel();
    private final validasi valid = new validasi();
    private final ApiBPJS api = new ApiBPJS();
    private final ObjectMapper objMap = new ObjectMapper();
    
    private String noRawat, noReg, kodePoliRS, kodeDokterRS, namaPj, alamatPj, hubunganPj, biayaReg, statusDaftar, statusPoli, umurDaftar, statusUmur;

    public DlgSMCRegistrasiSEPOnsite(java.awt.Frame parent, boolean id) {
        super(parent, id);
        initComponents();

        kodePPKPelayanan.setText(query.cariIsiSmc("select kode_ppk from setting limit 1"));
        namaPPKPelayanan.setText(query.cariIsiSmc("select nama_instansi from setting limit 1"));
        catatan.setText("Anjungan Pasien Mandiri RS Samarinda Medika Citra");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new component.Panel();
        jPanel2 = new component.Panel();
        namaPasien = new widget.TextBox();
        noRM = new widget.TextBox();
        noKartu = new widget.TextBox();
        jLabel20 = new widget.Label();
        tglSEP = new widget.Tanggal();
        jLabel22 = new widget.Label();
        tglRujuk = new widget.Tanggal();
        jLabel23 = new widget.Label();
        noRujukan = new widget.TextBox();
        jLabel9 = new widget.Label();
        kodePPKPelayanan = new widget.TextBox();
        namaPPKPelayanan = new widget.TextBox();
        jLabel10 = new widget.Label();
        kodePPK = new widget.TextBox();
        namaPPK = new widget.TextBox();
        jLabel11 = new widget.Label();
        kodeDiagnosa = new widget.TextBox();
        namaDiagnosa = new widget.TextBox();
        namaPoli = new widget.TextBox();
        kodePoli = new widget.TextBox();
        LabelPoli = new widget.Label();
        jLabel13 = new widget.Label();
        jLabel14 = new widget.Label();
        catatan = new widget.TextBox();
        jenisPelayanan = new widget.ComboBox();
        LabelKelas = new widget.Label();
        kelas = new widget.ComboBox();
        lakalantas = new widget.ComboBox();
        jLabel8 = new widget.Label();
        tglLahir = new widget.TextBox();
        jLabel18 = new widget.Label();
        jk = new widget.TextBox();
        jLabel24 = new widget.Label();
        jenisPeserta = new widget.TextBox();
        jLabel25 = new widget.Label();
        statusPeserta = new widget.TextBox();
        jLabel27 = new widget.Label();
        asalRujukan = new widget.ComboBox();
        noTelp = new widget.TextBox();
        katarak = new widget.ComboBox();
        jLabel37 = new widget.Label();
        jLabel38 = new widget.Label();
        tglKLL = new widget.Tanggal();
        LabelPoli2 = new widget.Label();
        kodeDokter = new widget.TextBox();
        namaDokter = new widget.TextBox();
        jLabel36 = new widget.Label();
        keterangan = new widget.TextBox();
        jLabel40 = new widget.Label();
        suplesi = new widget.ComboBox();
        noSEPSuplesi = new widget.TextBox();
        jLabel41 = new widget.Label();
        LabelPoli3 = new widget.Label();
        kodeProvKLL = new widget.TextBox();
        namaProvKLL = new widget.TextBox();
        LabelPoli4 = new widget.Label();
        kodeKabKLL = new widget.TextBox();
        namaKabKLL = new widget.TextBox();
        LabelPoli5 = new widget.Label();
        kodeKecKLL = new widget.TextBox();
        namaKecKLL = new widget.TextBox();
        jLabel42 = new widget.Label();
        tujuanKunjungan = new widget.ComboBox();
        flagProsedur = new widget.ComboBox();
        jLabel43 = new widget.Label();
        jLabel44 = new widget.Label();
        penunjang = new widget.ComboBox();
        jLabel45 = new widget.Label();
        asesmenPelayanan = new widget.ComboBox();
        kodeDPJPLayanan = new widget.TextBox();
        namaDPJPLayanan = new widget.TextBox();
        pilihDokter = new widget.Button();
        jLabel55 = new widget.Label();
        jLabel56 = new widget.Label();
        jLabel12 = new widget.Label();
        jLabel6 = new widget.Label();
        noSKDP = new widget.TextBox();
        jLabel26 = new widget.Label();
        nik = new widget.TextBox();
        jLabel7 = new widget.Label();
        pilihPoli = new widget.Button();
        pilihDiagnosa = new widget.Button();
        pilihRujukan = new widget.Button();
        riwayatPelayananBPJS = new widget.Button();
        LabelPoli7 = new widget.Label();
        approvalFP = new widget.Button();
        pengajuanFP = new widget.Button();
        lblTerapi = new widget.Label();
        kodePoliTerapi = new widget.TextBox();
        namaPoliTerapi = new widget.TextBox();
        pilihPoliTerapi = new widget.Button();
        kodeDokterTerapi = new widget.TextBox();
        namaDokterTerapi = new widget.TextBox();
        pilihDokterTerapi = new widget.Button();
        LabelPoli8 = new widget.Label();
        LabelPoli9 = new widget.Label();
        jPanel3 = new javax.swing.JPanel();
        daftar = new component.Button();
        fingerprint = new component.Button();
        batal = new component.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(1, 1));

        jPanel1.setBackground(new java.awt.Color(238, 238, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 238, 255), 1, true), "DATA ELIGIBILITAS PESERTA JKN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Inter Display", 0, 24), new java.awt.Color(0, 131, 62))); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(543, 106));
        jPanel1.setPreferredSize(new java.awt.Dimension(543, 106));
        jPanel1.setLayout(new java.awt.BorderLayout(0, 1));

        jPanel2.setBackground(new java.awt.Color(238, 238, 255));
        jPanel2.setForeground(new java.awt.Color(0, 131, 62));
        jPanel2.setPreferredSize(new java.awt.Dimension(390, 120));
        jPanel2.setLayout(null);

        namaPasien.setBackground(new java.awt.Color(245, 250, 240));
        namaPasien.setHighlighter(null);
        jPanel2.add(namaPasien);
        namaPasien.setBounds(340, 10, 230, 30);

        noRM.setEditable(false);
        noRM.setBackground(new java.awt.Color(245, 250, 240));
        noRM.setHighlighter(null);
        jPanel2.add(noRM);
        noRM.setBounds(230, 10, 110, 30);

        noKartu.setEditable(false);
        noKartu.setBackground(new java.awt.Color(255, 255, 153));
        noKartu.setHighlighter(null);
        jPanel2.add(noKartu);
        noKartu.setBounds(730, 70, 300, 30);

        jLabel20.setForeground(new java.awt.Color(0, 131, 62));
        jLabel20.setText("Tgl. SEP :");
        jLabel20.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel20.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel20);
        jLabel20.setBounds(625, 130, 100, 30);

        tglSEP.setEditable(false);
        tglSEP.setForeground(new java.awt.Color(50, 70, 50));
        tglSEP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "05-04-2024" }));
        tglSEP.setDisplayFormat("dd-MM-yyyy");
        tglSEP.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        tglSEP.setOpaque(false);
        tglSEP.setPreferredSize(new java.awt.Dimension(95, 25));
        jPanel2.add(tglSEP);
        tglSEP.setBounds(730, 130, 170, 30);

        jLabel22.setForeground(new java.awt.Color(0, 131, 62));
        jLabel22.setText("Tgl. Rujuk :");
        jLabel22.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel22.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel22);
        jLabel22.setBounds(625, 160, 100, 30);

        tglRujuk.setEditable(false);
        tglRujuk.setForeground(new java.awt.Color(50, 70, 50));
        tglRujuk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "05-04-2024" }));
        tglRujuk.setDisplayFormat("dd-MM-yyyy");
        tglRujuk.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        tglRujuk.setOpaque(false);
        tglRujuk.setPreferredSize(new java.awt.Dimension(95, 23));
        jPanel2.add(tglRujuk);
        tglRujuk.setBounds(730, 160, 170, 30);

        jLabel23.setForeground(new java.awt.Color(0, 131, 62));
        jLabel23.setText("No. SKDP / S. Kontrol :");
        jLabel23.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel23.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel23);
        jLabel23.setBounds(90, 70, 135, 30);

        noRujukan.setEditable(false);
        noRujukan.setBackground(new java.awt.Color(255, 255, 153));
        noRujukan.setHighlighter(null);
        jPanel2.add(noRujukan);
        noRujukan.setBounds(230, 100, 340, 30);

        jLabel9.setForeground(new java.awt.Color(0, 131, 62));
        jLabel9.setText("PPK Pelayanan :");
        jLabel9.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel9);
        jLabel9.setBounds(90, 250, 135, 30);

        kodePPKPelayanan.setEditable(false);
        kodePPKPelayanan.setBackground(new java.awt.Color(245, 250, 240));
        kodePPKPelayanan.setHighlighter(null);
        jPanel2.add(kodePPKPelayanan);
        kodePPKPelayanan.setBounds(230, 250, 75, 30);

        namaPPKPelayanan.setEditable(false);
        namaPPKPelayanan.setBackground(new java.awt.Color(245, 250, 240));
        namaPPKPelayanan.setHighlighter(null);
        jPanel2.add(namaPPKPelayanan);
        namaPPKPelayanan.setBounds(310, 250, 260, 30);

        jLabel10.setForeground(new java.awt.Color(0, 131, 62));
        jLabel10.setText("PPK Rujukan :");
        jLabel10.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel10);
        jLabel10.setBounds(90, 130, 135, 30);

        kodePPK.setEditable(false);
        kodePPK.setBackground(new java.awt.Color(245, 250, 240));
        kodePPK.setHighlighter(null);
        jPanel2.add(kodePPK);
        kodePPK.setBounds(230, 130, 75, 30);

        namaPPK.setEditable(false);
        namaPPK.setBackground(new java.awt.Color(245, 250, 240));
        namaPPK.setHighlighter(null);
        jPanel2.add(namaPPK);
        namaPPK.setBounds(310, 130, 260, 30);

        jLabel11.setForeground(new java.awt.Color(0, 131, 62));
        jLabel11.setText("Diagnosa Awal :");
        jLabel11.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel11);
        jLabel11.setBounds(90, 160, 135, 30);

        kodeDiagnosa.setEditable(false);
        kodeDiagnosa.setBackground(new java.awt.Color(255, 255, 153));
        kodeDiagnosa.setHighlighter(null);
        jPanel2.add(kodeDiagnosa);
        kodeDiagnosa.setBounds(230, 160, 75, 30);

        namaDiagnosa.setEditable(false);
        namaDiagnosa.setBackground(new java.awt.Color(255, 255, 153));
        namaDiagnosa.setHighlighter(null);
        jPanel2.add(namaDiagnosa);
        namaDiagnosa.setBounds(310, 160, 260, 30);

        namaPoli.setEditable(false);
        namaPoli.setBackground(new java.awt.Color(255, 255, 153));
        namaPoli.setHighlighter(null);
        jPanel2.add(namaPoli);
        namaPoli.setBounds(310, 190, 260, 30);

        kodePoli.setEditable(false);
        kodePoli.setBackground(new java.awt.Color(255, 255, 153));
        kodePoli.setHighlighter(null);
        jPanel2.add(kodePoli);
        kodePoli.setBounds(230, 190, 75, 30);

        LabelPoli.setForeground(new java.awt.Color(0, 131, 62));
        LabelPoli.setText("Poli Tujuan :");
        LabelPoli.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        LabelPoli.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(LabelPoli);
        LabelPoli.setBounds(90, 190, 135, 30);

        jLabel13.setForeground(new java.awt.Color(0, 131, 62));
        jLabel13.setText("Jenis Pelayanan");
        jLabel13.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel13);
        jLabel13.setBounds(90, 280, 135, 30);

        jLabel14.setForeground(new java.awt.Color(0, 131, 62));
        jLabel14.setText("Catatan :");
        jLabel14.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jPanel2.add(jLabel14);
        jLabel14.setBounds(625, 460, 100, 30);

        catatan.setEditable(false);
        catatan.setBackground(new java.awt.Color(245, 250, 240));
        catatan.setHighlighter(null);
        jPanel2.add(catatan);
        catatan.setBounds(730, 460, 300, 30);

        jenisPelayanan.setBackground(new java.awt.Color(255, 255, 153));
        jenisPelayanan.setForeground(new java.awt.Color(0, 131, 62));
        jenisPelayanan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1. Ranap", "2. Ralan" }));
        jenisPelayanan.setSelectedIndex(1);
        jenisPelayanan.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jPanel2.add(jenisPelayanan);
        jenisPelayanan.setBounds(230, 280, 110, 30);

        LabelKelas.setForeground(new java.awt.Color(0, 131, 62));
        LabelKelas.setText("Kelas :");
        LabelKelas.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jPanel2.add(LabelKelas);
        LabelKelas.setBounds(350, 280, 50, 30);

        kelas.setForeground(new java.awt.Color(0, 131, 62));
        kelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1. Kelas 1", "2. Kelas 2", "3. Kelas 3" }));
        kelas.setSelectedIndex(2);
        kelas.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jPanel2.add(kelas);
        kelas.setBounds(405, 280, 100, 30);

        lakalantas.setForeground(new java.awt.Color(0, 131, 62));
        lakalantas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0. Bukan KLL", "1. KLL Bukan KK", "2. KLL dan KK", "3. KK" }));
        lakalantas.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        lakalantas.setPreferredSize(new java.awt.Dimension(64, 25));
        lakalantas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lakalantasItemStateChanged(evt);
            }
        });
        jPanel2.add(lakalantas);
        lakalantas.setBounds(730, 250, 170, 30);

        jLabel8.setForeground(new java.awt.Color(0, 131, 62));
        jLabel8.setText("Data Pasien : ");
        jLabel8.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel8);
        jLabel8.setBounds(90, 10, 135, 30);

        tglLahir.setEditable(false);
        tglLahir.setBackground(new java.awt.Color(245, 250, 240));
        tglLahir.setHighlighter(null);
        jPanel2.add(tglLahir);
        tglLahir.setBounds(230, 40, 110, 30);

        jLabel18.setForeground(new java.awt.Color(0, 131, 62));
        jLabel18.setText("J.K :");
        jLabel18.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jPanel2.add(jLabel18);
        jLabel18.setBounds(905, 10, 30, 30);

        jk.setEditable(false);
        jk.setBackground(new java.awt.Color(245, 250, 240));
        jk.setHighlighter(null);
        jPanel2.add(jk);
        jk.setBounds(940, 10, 90, 30);

        jLabel24.setForeground(new java.awt.Color(0, 131, 62));
        jLabel24.setText("Peserta :");
        jLabel24.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel24.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel24);
        jLabel24.setBounds(625, 10, 100, 30);

        jenisPeserta.setEditable(false);
        jenisPeserta.setBackground(new java.awt.Color(245, 250, 240));
        jenisPeserta.setHighlighter(null);
        jPanel2.add(jenisPeserta);
        jenisPeserta.setBounds(730, 10, 173, 30);

        jLabel25.setForeground(new java.awt.Color(0, 131, 62));
        jLabel25.setText("Status :");
        jLabel25.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel25.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel25);
        jLabel25.setBounds(370, 40, 50, 30);

        statusPeserta.setEditable(false);
        statusPeserta.setBackground(new java.awt.Color(245, 250, 240));
        statusPeserta.setHighlighter(null);
        jPanel2.add(statusPeserta);
        statusPeserta.setBounds(420, 40, 150, 30);

        jLabel27.setForeground(new java.awt.Color(0, 131, 62));
        jLabel27.setText("Asal Rujukan :");
        jLabel27.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jPanel2.add(jLabel27);
        jLabel27.setBounds(625, 100, 100, 30);

        asalRujukan.setForeground(new java.awt.Color(0, 131, 62));
        asalRujukan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1. Faskes 1", "2. Faskes 2(RS)" }));
        asalRujukan.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jPanel2.add(asalRujukan);
        asalRujukan.setBounds(730, 100, 170, 30);

        noTelp.setHighlighter(null);
        jPanel2.add(noTelp);
        noTelp.setBounds(730, 190, 170, 30);

        katarak.setForeground(new java.awt.Color(0, 131, 62));
        katarak.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0. Tidak", "1.Ya" }));
        katarak.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        katarak.setPreferredSize(new java.awt.Dimension(64, 25));
        jPanel2.add(katarak);
        katarak.setBounds(730, 220, 170, 30);

        jLabel37.setForeground(new java.awt.Color(0, 131, 62));
        jLabel37.setText("Katarak :");
        jLabel37.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jPanel2.add(jLabel37);
        jLabel37.setBounds(625, 220, 100, 30);

        jLabel38.setForeground(new java.awt.Color(0, 131, 62));
        jLabel38.setText("Tgl. KLL :");
        jLabel38.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel38.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel38);
        jLabel38.setBounds(625, 280, 100, 30);

        tglKLL.setEditable(false);
        tglKLL.setForeground(new java.awt.Color(50, 70, 50));
        tglKLL.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "05-04-2024" }));
        tglKLL.setDisplayFormat("dd-MM-yyyy");
        tglKLL.setEnabled(false);
        tglKLL.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        tglKLL.setOpaque(false);
        tglKLL.setPreferredSize(new java.awt.Dimension(64, 25));
        jPanel2.add(tglKLL);
        tglKLL.setBounds(730, 280, 170, 30);

        LabelPoli2.setForeground(new java.awt.Color(0, 131, 62));
        LabelPoli2.setText("Dokter DPJP :");
        LabelPoli2.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        LabelPoli2.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(LabelPoli2);
        LabelPoli2.setBounds(90, 220, 135, 30);

        kodeDokter.setEditable(false);
        kodeDokter.setBackground(new java.awt.Color(255, 255, 153));
        kodeDokter.setHighlighter(null);
        jPanel2.add(kodeDokter);
        kodeDokter.setBounds(230, 220, 75, 30);

        namaDokter.setEditable(false);
        namaDokter.setBackground(new java.awt.Color(255, 255, 153));
        namaDokter.setHighlighter(null);
        jPanel2.add(namaDokter);
        namaDokter.setBounds(310, 220, 260, 30);

        jLabel36.setForeground(new java.awt.Color(0, 131, 62));
        jLabel36.setText("Keterangan :");
        jLabel36.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel36.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel36);
        jLabel36.setBounds(625, 310, 100, 30);

        keterangan.setEditable(false);
        keterangan.setBackground(new java.awt.Color(245, 250, 240));
        keterangan.setHighlighter(null);
        jPanel2.add(keterangan);
        keterangan.setBounds(730, 310, 300, 30);

        jLabel40.setForeground(new java.awt.Color(0, 131, 62));
        jLabel40.setText("Suplesi :");
        jLabel40.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jPanel2.add(jLabel40);
        jLabel40.setBounds(625, 340, 100, 30);

        suplesi.setForeground(new java.awt.Color(0, 131, 62));
        suplesi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0. Tidak", "1.Ya" }));
        suplesi.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        suplesi.setPreferredSize(new java.awt.Dimension(64, 25));
        jPanel2.add(suplesi);
        suplesi.setBounds(730, 340, 90, 30);

        noSEPSuplesi.setHighlighter(null);
        jPanel2.add(noSEPSuplesi);
        noSEPSuplesi.setBounds(890, 340, 140, 30);

        jLabel41.setForeground(new java.awt.Color(0, 131, 62));
        jLabel41.setText("Suplesi :");
        jLabel41.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel41.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel41);
        jLabel41.setBounds(835, 340, 50, 30);

        LabelPoli3.setForeground(new java.awt.Color(0, 131, 62));
        LabelPoli3.setText("Propinsi KLL :");
        LabelPoli3.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jPanel2.add(LabelPoli3);
        LabelPoli3.setBounds(625, 370, 100, 30);

        kodeProvKLL.setEditable(false);
        kodeProvKLL.setBackground(new java.awt.Color(245, 250, 240));
        kodeProvKLL.setHighlighter(null);
        jPanel2.add(kodeProvKLL);
        kodeProvKLL.setBounds(730, 370, 55, 30);

        namaProvKLL.setEditable(false);
        namaProvKLL.setBackground(new java.awt.Color(245, 250, 240));
        namaProvKLL.setHighlighter(null);
        jPanel2.add(namaProvKLL);
        namaProvKLL.setBounds(790, 370, 240, 30);

        LabelPoli4.setForeground(new java.awt.Color(0, 131, 62));
        LabelPoli4.setText("Kabupaten KLL :");
        LabelPoli4.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jPanel2.add(LabelPoli4);
        LabelPoli4.setBounds(625, 400, 100, 30);

        kodeKabKLL.setEditable(false);
        kodeKabKLL.setBackground(new java.awt.Color(245, 250, 240));
        kodeKabKLL.setHighlighter(null);
        jPanel2.add(kodeKabKLL);
        kodeKabKLL.setBounds(730, 400, 55, 30);

        namaKabKLL.setEditable(false);
        namaKabKLL.setBackground(new java.awt.Color(245, 250, 240));
        namaKabKLL.setHighlighter(null);
        jPanel2.add(namaKabKLL);
        namaKabKLL.setBounds(790, 400, 240, 30);

        LabelPoli5.setForeground(new java.awt.Color(0, 131, 62));
        LabelPoli5.setText("Kecamatan KLL :");
        LabelPoli5.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jPanel2.add(LabelPoli5);
        LabelPoli5.setBounds(625, 430, 100, 30);

        kodeKecKLL.setEditable(false);
        kodeKecKLL.setBackground(new java.awt.Color(245, 250, 240));
        kodeKecKLL.setHighlighter(null);
        jPanel2.add(kodeKecKLL);
        kodeKecKLL.setBounds(730, 430, 55, 30);

        namaKecKLL.setEditable(false);
        namaKecKLL.setBackground(new java.awt.Color(245, 250, 240));
        namaKecKLL.setHighlighter(null);
        jPanel2.add(namaKecKLL);
        namaKecKLL.setBounds(790, 430, 240, 30);

        jLabel42.setForeground(new java.awt.Color(0, 131, 62));
        jLabel42.setText("Tujuan Kunjungan :");
        jLabel42.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel42.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel42);
        jLabel42.setBounds(90, 310, 135, 30);

        tujuanKunjungan.setBackground(new java.awt.Color(255, 255, 153));
        tujuanKunjungan.setForeground(new java.awt.Color(0, 131, 62));
        tujuanKunjungan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0. Normal", "1. Prosedur", "2. Konsul Dokter" }));
        tujuanKunjungan.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jPanel2.add(tujuanKunjungan);
        tujuanKunjungan.setBounds(230, 310, 340, 30);

        flagProsedur.setBackground(new java.awt.Color(255, 255, 153));
        flagProsedur.setForeground(new java.awt.Color(0, 131, 62));
        flagProsedur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "0. Prosedur Tidak Berkelanjutan", "1. Prosedur dan Terapi Berkelanjutan" }));
        flagProsedur.setEnabled(false);
        flagProsedur.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jPanel2.add(flagProsedur);
        flagProsedur.setBounds(230, 340, 340, 30);

        jLabel43.setForeground(new java.awt.Color(0, 131, 62));
        jLabel43.setText("Flag Prosedur :");
        jLabel43.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel43.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel43);
        jLabel43.setBounds(90, 340, 135, 30);

        jLabel44.setForeground(new java.awt.Color(0, 131, 62));
        jLabel44.setText("Penunjang :");
        jLabel44.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel44.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel44);
        jLabel44.setBounds(90, 370, 135, 30);

        penunjang.setBackground(new java.awt.Color(255, 255, 153));
        penunjang.setForeground(new java.awt.Color(0, 131, 62));
        penunjang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1. Radioterapi", "2. Kemoterapi", "3. Rehabilitasi Medik", "4. Rehabilitasi Psikososial", "5. Transfusi Darah", "6. Pelayanan Gigi", "7. Laboratorium", "8. USG", "9. Farmasi", "10. Lain-Lain", "11. MRI", "12. HEMODIALISA" }));
        penunjang.setEnabled(false);
        penunjang.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jPanel2.add(penunjang);
        penunjang.setBounds(230, 370, 340, 30);

        jLabel45.setForeground(new java.awt.Color(0, 131, 62));
        jLabel45.setText("Asesmen Pelayanan :");
        jLabel45.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel45.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel45);
        jLabel45.setBounds(90, 400, 135, 30);

        asesmenPelayanan.setBackground(new java.awt.Color(255, 255, 153));
        asesmenPelayanan.setForeground(new java.awt.Color(0, 131, 62));
        asesmenPelayanan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1. Poli spesialis tidak tersedia pada hari sebelumnya", "2. Jam Poli telah berakhir pada hari sebelumnya", "3. Spesialis yang dimaksud tidak praktek pada hari sebelumnya", "4. Atas Instruksi RS", "5. Tujuan Kontrol" }));
        asesmenPelayanan.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jPanel2.add(asesmenPelayanan);
        asesmenPelayanan.setBounds(230, 400, 340, 30);

        kodeDPJPLayanan.setEditable(false);
        kodeDPJPLayanan.setBackground(new java.awt.Color(255, 255, 153));
        kodeDPJPLayanan.setHighlighter(null);
        jPanel2.add(kodeDPJPLayanan);
        kodeDPJPLayanan.setBounds(230, 430, 80, 30);

        namaDPJPLayanan.setEditable(false);
        namaDPJPLayanan.setBackground(new java.awt.Color(255, 255, 153));
        namaDPJPLayanan.setHighlighter(null);
        jPanel2.add(namaDPJPLayanan);
        namaDPJPLayanan.setBounds(310, 430, 260, 30);

        pilihDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/pilih.png"))); // NOI18N
        pilihDokter.setMnemonic('X');
        pilihDokter.setToolTipText("Alt+X");
        pilihDokter.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        pilihDokter.setGlassColor(new java.awt.Color(238, 238, 255));
        jPanel2.add(pilihDokter);
        pilihDokter.setBounds(570, 220, 40, 30);

        jLabel55.setForeground(new java.awt.Color(0, 131, 62));
        jLabel55.setText("Laka Lantas :");
        jLabel55.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jPanel2.add(jLabel55);
        jLabel55.setBounds(625, 250, 100, 30);

        jLabel56.setForeground(new java.awt.Color(0, 131, 62));
        jLabel56.setText("No. Telp :");
        jLabel56.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel56.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel56);
        jLabel56.setBounds(625, 190, 100, 30);

        jLabel12.setForeground(new java.awt.Color(0, 131, 62));
        jLabel12.setText("Tgl. Lahir :");
        jLabel12.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel12.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel12);
        jLabel12.setBounds(90, 40, 135, 30);

        jLabel6.setForeground(new java.awt.Color(0, 131, 62));
        jLabel6.setText("NIK :");
        jLabel6.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(625, 40, 100, 30);

        noSKDP.setEditable(false);
        noSKDP.setBackground(new java.awt.Color(255, 255, 153));
        noSKDP.setHighlighter(null);
        jPanel2.add(noSKDP);
        noSKDP.setBounds(230, 70, 340, 30);

        jLabel26.setForeground(new java.awt.Color(0, 131, 62));
        jLabel26.setText("No. Rujukan :");
        jLabel26.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel26.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(jLabel26);
        jLabel26.setBounds(90, 100, 135, 30);

        nik.setEditable(false);
        nik.setBackground(new java.awt.Color(255, 255, 153));
        nik.setHighlighter(null);
        jPanel2.add(nik);
        nik.setBounds(730, 40, 300, 30);

        jLabel7.setForeground(new java.awt.Color(0, 131, 62));
        jLabel7.setText("No. Kartu :");
        jLabel7.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(625, 70, 100, 30);

        pilihPoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/pilih.png"))); // NOI18N
        pilihPoli.setMnemonic('X');
        pilihPoli.setToolTipText("Alt+X");
        pilihPoli.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        pilihPoli.setGlassColor(new java.awt.Color(238, 238, 255));
        jPanel2.add(pilihPoli);
        pilihPoli.setBounds(570, 190, 40, 30);

        pilihDiagnosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/pilih.png"))); // NOI18N
        pilihDiagnosa.setMnemonic('X');
        pilihDiagnosa.setToolTipText("Alt+X");
        pilihDiagnosa.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        pilihDiagnosa.setGlassColor(new java.awt.Color(238, 238, 255));
        jPanel2.add(pilihDiagnosa);
        pilihDiagnosa.setBounds(570, 160, 40, 30);

        pilihRujukan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/pilih.png"))); // NOI18N
        pilihRujukan.setMnemonic('X');
        pilihRujukan.setToolTipText("Alt+X");
        pilihRujukan.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        pilihRujukan.setGlassColor(new java.awt.Color(238, 238, 255));
        jPanel2.add(pilihRujukan);
        pilihRujukan.setBounds(570, 100, 40, 30);

        riwayatPelayananBPJS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/pilih.png"))); // NOI18N
        riwayatPelayananBPJS.setMnemonic('X');
        riwayatPelayananBPJS.setText("Riwayat Layanan BPJS");
        riwayatPelayananBPJS.setToolTipText("Alt+X");
        riwayatPelayananBPJS.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        riwayatPelayananBPJS.setGlassColor(new java.awt.Color(238, 238, 255));
        riwayatPelayananBPJS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(riwayatPelayananBPJS);
        riwayatPelayananBPJS.setBounds(1040, 150, 220, 30);

        LabelPoli7.setForeground(new java.awt.Color(0, 131, 62));
        LabelPoli7.setText("Dokter Terapi :");
        LabelPoli7.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        LabelPoli7.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(LabelPoli7);
        LabelPoli7.setBounds(90, 520, 135, 30);

        approvalFP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/approvalfp.png"))); // NOI18N
        approvalFP.setMnemonic('X');
        approvalFP.setText("Approval FP BPJS");
        approvalFP.setToolTipText("Alt+X");
        approvalFP.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        approvalFP.setGlassColor(new java.awt.Color(238, 238, 255));
        approvalFP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(approvalFP);
        approvalFP.setBounds(1040, 260, 190, 50);

        pengajuanFP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/pengajuan.png"))); // NOI18N
        pengajuanFP.setMnemonic('X');
        pengajuanFP.setText("Pengajuan FP BPJS");
        pengajuanFP.setToolTipText("Alt+X");
        pengajuanFP.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        pengajuanFP.setGlassColor(new java.awt.Color(238, 238, 255));
        pengajuanFP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(pengajuanFP);
        pengajuanFP.setBounds(1040, 200, 190, 50);

        lblTerapi.setForeground(new java.awt.Color(0, 131, 62));
        lblTerapi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTerapi.setText("Terapi / Rehabilitasi Medik");
        lblTerapi.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        lblTerapi.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(lblTerapi);
        lblTerapi.setBounds(230, 470, 340, 20);

        kodePoliTerapi.setEditable(false);
        kodePoliTerapi.setBackground(new java.awt.Color(255, 255, 153));
        kodePoliTerapi.setHighlighter(null);
        jPanel2.add(kodePoliTerapi);
        kodePoliTerapi.setBounds(230, 490, 75, 30);

        namaPoliTerapi.setEditable(false);
        namaPoliTerapi.setBackground(new java.awt.Color(255, 255, 153));
        namaPoliTerapi.setHighlighter(null);
        jPanel2.add(namaPoliTerapi);
        namaPoliTerapi.setBounds(310, 490, 260, 30);

        pilihPoliTerapi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/pilih.png"))); // NOI18N
        pilihPoliTerapi.setMnemonic('X');
        pilihPoliTerapi.setToolTipText("Alt+X");
        pilihPoliTerapi.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        pilihPoliTerapi.setGlassColor(new java.awt.Color(238, 238, 255));
        jPanel2.add(pilihPoliTerapi);
        pilihPoliTerapi.setBounds(570, 490, 40, 30);

        kodeDokterTerapi.setEditable(false);
        kodeDokterTerapi.setBackground(new java.awt.Color(255, 255, 153));
        kodeDokterTerapi.setHighlighter(null);
        jPanel2.add(kodeDokterTerapi);
        kodeDokterTerapi.setBounds(230, 520, 75, 30);

        namaDokterTerapi.setEditable(false);
        namaDokterTerapi.setBackground(new java.awt.Color(255, 255, 153));
        namaDokterTerapi.setHighlighter(null);
        jPanel2.add(namaDokterTerapi);
        namaDokterTerapi.setBounds(310, 520, 260, 30);

        pilihDokterTerapi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/pilih.png"))); // NOI18N
        pilihDokterTerapi.setMnemonic('X');
        pilihDokterTerapi.setToolTipText("Alt+X");
        pilihDokterTerapi.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        pilihDokterTerapi.setGlassColor(new java.awt.Color(238, 238, 255));
        jPanel2.add(pilihDokterTerapi);
        pilihDokterTerapi.setBounds(570, 520, 40, 30);

        LabelPoli8.setForeground(new java.awt.Color(0, 131, 62));
        LabelPoli8.setText("DPJP Layanan :");
        LabelPoli8.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        LabelPoli8.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(LabelPoli8);
        LabelPoli8.setBounds(90, 430, 135, 30);

        LabelPoli9.setForeground(new java.awt.Color(0, 131, 62));
        LabelPoli9.setText("Poli Terapi :");
        LabelPoli9.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        LabelPoli9.setPreferredSize(new java.awt.Dimension(55, 23));
        jPanel2.add(LabelPoli9);
        LabelPoli9.setBounds(90, 490, 135, 30);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(238, 238, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(533, 120));
        jPanel3.setPreferredSize(new java.awt.Dimension(533, 120));

        daftar.setForeground(new java.awt.Color(0, 131, 62));
        daftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/konfirmasi.png"))); // NOI18N
        daftar.setMnemonic('S');
        daftar.setText("Konfirmasi");
        daftar.setToolTipText("Alt+S");
        daftar.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        daftar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        daftar.setPreferredSize(new java.awt.Dimension(300, 45));
        jPanel3.add(daftar);

        fingerprint.setForeground(new java.awt.Color(0, 131, 62));
        fingerprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/fingerprint.png"))); // NOI18N
        fingerprint.setMnemonic('K');
        fingerprint.setText("FINGERPRINT BPJS");
        fingerprint.setToolTipText("Alt+K");
        fingerprint.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        fingerprint.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        fingerprint.setPreferredSize(new java.awt.Dimension(300, 45));
        jPanel3.add(fingerprint);

        batal.setForeground(new java.awt.Color(0, 131, 62));
        batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/reset.png"))); // NOI18N
        batal.setMnemonic('K');
        batal.setText("Batal");
        batal.setToolTipText("Alt+K");
        batal.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        batal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        batal.setPreferredSize(new java.awt.Dimension(300, 45));
        jPanel3.add(batal);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lakalantasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lakalantasItemStateChanged
        if (evt.getID() == 0) {
            tglKLL.setEnabled(false);
            keterangan.setEnabled(false);
            keterangan.setText("");
        } else {
            tglKLL.setEnabled(true);
            keterangan.setEnabled(true);
        }
    }//GEN-LAST:event_lakalantasItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgSMCRegistrasiSEPOnsite dialog = new DlgSMCRegistrasiSEPOnsite(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Label LabelKelas;
    private widget.Label LabelPoli;
    private widget.Label LabelPoli2;
    private widget.Label LabelPoli3;
    private widget.Label LabelPoli4;
    private widget.Label LabelPoli5;
    private widget.Label LabelPoli7;
    private widget.Label LabelPoli8;
    private widget.Label LabelPoli9;
    private widget.Button approvalFP;
    private widget.ComboBox asalRujukan;
    private widget.ComboBox asesmenPelayanan;
    private component.Button batal;
    private widget.TextBox catatan;
    private component.Button daftar;
    private component.Button fingerprint;
    private widget.ComboBox flagProsedur;
    private widget.Label jLabel10;
    private widget.Label jLabel11;
    private widget.Label jLabel12;
    private widget.Label jLabel13;
    private widget.Label jLabel14;
    private widget.Label jLabel18;
    private widget.Label jLabel20;
    private widget.Label jLabel22;
    private widget.Label jLabel23;
    private widget.Label jLabel24;
    private widget.Label jLabel25;
    private widget.Label jLabel26;
    private widget.Label jLabel27;
    private widget.Label jLabel36;
    private widget.Label jLabel37;
    private widget.Label jLabel38;
    private widget.Label jLabel40;
    private widget.Label jLabel41;
    private widget.Label jLabel42;
    private widget.Label jLabel43;
    private widget.Label jLabel44;
    private widget.Label jLabel45;
    private widget.Label jLabel55;
    private widget.Label jLabel56;
    private widget.Label jLabel6;
    private widget.Label jLabel7;
    private widget.Label jLabel8;
    private widget.Label jLabel9;
    private component.Panel jPanel1;
    private component.Panel jPanel2;
    private javax.swing.JPanel jPanel3;
    private widget.ComboBox jenisPelayanan;
    private widget.TextBox jenisPeserta;
    private widget.TextBox jk;
    private widget.ComboBox katarak;
    private widget.ComboBox kelas;
    private widget.TextBox keterangan;
    private widget.TextBox kodeDPJPLayanan;
    private widget.TextBox kodeDiagnosa;
    private widget.TextBox kodeDokter;
    private widget.TextBox kodeDokterTerapi;
    private widget.TextBox kodeKabKLL;
    private widget.TextBox kodeKecKLL;
    private widget.TextBox kodePPK;
    private widget.TextBox kodePPKPelayanan;
    private widget.TextBox kodePoli;
    private widget.TextBox kodePoliTerapi;
    private widget.TextBox kodeProvKLL;
    private widget.ComboBox lakalantas;
    private widget.Label lblTerapi;
    private widget.TextBox namaDPJPLayanan;
    private widget.TextBox namaDiagnosa;
    private widget.TextBox namaDokter;
    private widget.TextBox namaDokterTerapi;
    private widget.TextBox namaKabKLL;
    private widget.TextBox namaKecKLL;
    private widget.TextBox namaPPK;
    private widget.TextBox namaPPKPelayanan;
    private widget.TextBox namaPasien;
    private widget.TextBox namaPoli;
    private widget.TextBox namaPoliTerapi;
    private widget.TextBox namaProvKLL;
    private widget.TextBox nik;
    private widget.TextBox noKartu;
    private widget.TextBox noRM;
    private widget.TextBox noRujukan;
    private widget.TextBox noSEPSuplesi;
    private widget.TextBox noSKDP;
    private widget.TextBox noTelp;
    private widget.Button pengajuanFP;
    private widget.ComboBox penunjang;
    private widget.Button pilihDiagnosa;
    private widget.Button pilihDokter;
    private widget.Button pilihDokterTerapi;
    private widget.Button pilihPoli;
    private widget.Button pilihPoliTerapi;
    private widget.Button pilihRujukan;
    private widget.Button riwayatPelayananBPJS;
    private widget.TextBox statusPeserta;
    private widget.ComboBox suplesi;
    private widget.Tanggal tglKLL;
    private widget.TextBox tglLahir;
    private widget.Tanggal tglRujuk;
    private widget.Tanggal tglSEP;
    private widget.ComboBox tujuanKunjungan;
    // End of variables declaration//GEN-END:variables

    public void tampilRujukanPertama(String input) {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        JsonNode rujukan = cekRujukan(input, false);
        asalRujukan.setSelectedIndex(0);
        if (rujukan == null) {
            rujukan = cekRujukan(input, true);
            asalRujukan.setSelectedIndex(1);
        }

        if (rujukan == null) {
            JOptionPane.showMessageDialog(rootPane, "Rujukan tidak ditemukan...!!!");
            this.setCursor(Cursor.getDefaultCursor());
            return;
        }

        noRM.setText(query.cariIsiSmc("select no_rkm_medis from pasien where no_peserta = ?", input));
        namaPasien.setText(rujukan.path("pasien").path("nama").asText());
        tglLahir.setText(valid.SetTgl(rujukan.path("pasien").path("tglLahir").asText()));
        statusPeserta.setText(rujukan.path("pasien").path("statusPeserta").path("kode").asText() + " " + rujukan.path("pasien").path("statusPeserta").path("keterangan").asText());
        noRujukan.setText(rujukan.path("noKunjungan").asText());
        kodePPK.setText(rujukan.path("provPerujuk").path("kode").asText());
        namaPPK.setText(rujukan.path("provPerujuk").path("nama").asText());
        kodeDiagnosa.setText(rujukan.path("diagnosa").path("kode").asText());
        namaDiagnosa.setText(rujukan.path("diagnosa").path("nama").asText());
        kodePoli.setText(rujukan.path("poliRujukan").path("kode").asText());
        namaPoli.setText(rujukan.path("poliRujukan").path("nama").asText());
        jenisPelayanan.setSelectedIndex(0);
        switch (rujukan.path("hakKelas").path("kode").asText()) {
            case "1": kelas.setSelectedIndex(0); break;
            case "2": kelas.setSelectedIndex(1); break;
            case "3": kelas.setSelectedIndex(2); break;
        }
        kodeDPJPLayanan.setVisible(false);
        namaDPJPLayanan.setVisible(false);
        LabelPoli7.setVisible(false);
        jenisPeserta.setText(rujukan.path("pasien").path("jenisPeserta").path("keterangan").asText());
        jk.setText(rujukan.path("pasien").path("sex").asText());
        
        String _nik = rujukan.path("pasien").path("nik").asText().replace("null,", "");
        if (_nik.isBlank()) _nik = query.cariIsiSmc("select no_ktp from pasien where no_rkm_medis = ?", noRM.getText());
        nik.setText(_nik);
        
        noKartu.setText(rujukan.path("pasien").path("noKartu").asText());
        tglSEP.setDate(new Date());
        tglRujuk.setSelectedItem(valid.SetTgl(rujukan.path("tglKunjungan").asText()));
        
        String _noTelp = rujukan.path("pasien").path("mr").path("noTelepon").asText().replace("null", "");
        if (_noTelp.isBlank()) _noTelp = query.cariIsiSmc("select no_tlp from pasien where no_rkm_medis = ?", noRM.getText());
        noTelp.setText(_noTelp);

        this.setCursor(Cursor.getDefaultCursor());
    }
    
    public void tampilRujukanBedaPoli(String input) {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        
        kodeDPJPLayanan.setVisible(false);
        namaDPJPLayanan.setVisible(false);
        LabelPoli7.setVisible(false);
        
        this.setCursor(Cursor.getDefaultCursor());
    }

    public void tampilRujukanKontrol(String input) {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        
        kodeDPJPLayanan.setVisible(true);
        namaDPJPLayanan.setVisible(true);
        LabelPoli8.setVisible(true);
        
        //
        
        this.setCursor(Cursor.getDefaultCursor());
    }
    
    private JsonNode cekRujukan(String noKartu, boolean fktrl) {
        String url = koneksiDB.URLAPIBPJS() + "/Rujukan/Peserta/" + noKartu;
        if (fktrl) {
            url = koneksiDB.URLAPIBPJS() + "/Rujukan/RS/Peserta/" + noKartu;
        }

        try {
            String utc = api.getUTCDateTime();

            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            headers.add("X-Cons-ID", koneksiDB.CONSIDAPIBPJS());
            headers.add("X-Timestamp", utc);
            headers.add("X-Signature", api.getHmac(utc));
            headers.add("user_key", koneksiDB.USERKEYAPIBPJS());

            HttpEntity entities = new HttpEntity(headers);
            JsonNode root = objMap.readTree(api.getRest().exchange(url, HttpMethod.GET, entities, String.class).getBody());
            JsonNode metadata = root.path("metaData");
            JsonNode response = objMap.readTree(api.Decrypt(root.path("response").asText(), utc));
            JsonNode rujukan = response.path("rujukan");

            if (!metadata.path("code").asText().equals("200")) {
                System.out.println("Respon BPJS : " + metadata.path("message").asText());
            }

            return rujukan;
        } catch (Exception e) {
            System.out.println("Notif : " + e);
            if (e.toString().contains("UnknownHostException")) {
                JOptionPane.showMessageDialog(rootPane, "Koneksi ke server BPJS terputus!");
            }
            return null;
        }
    }

    private void autonomor() {
        switch (koneksiDB.URUTNOREG()) {
            case "dokter":
                noReg = query.cariIsiSmc(
                    "select lpad(ifnull(max(convert(no_reg, signed)), 0) + 1, 3, '0') from reg_periksa where kd_dokter = ? and tgl_registrasi = ?",
                    kodeDokterRS, valid.SetTgl(tglSEP.getSelectedItem().toString())
                );
                break;
            case "poli":
                noReg = query.cariIsiSmc(
                    "select lpad(ifnull(max(convert(no_reg, signed)), 0) + 1, 3, '0') from reg_periksa where kd_poli = ? and tgl_registrasi = ?",
                    kodePoliRS, valid.SetTgl(tglSEP.getSelectedItem().toString())
                );
                break;
            case "dokter + poli":
                noReg = query.cariIsiSmc(
                    "select lpad(ifnull(max(convert(no_reg, signed)), 0) + 1, 3, '0') from reg_periksa where kd_dokter = ? and kd_poli = ? and tgl_registrasi = ?",
                    kodeDokterRS, kodePoliRS, valid.SetTgl(tglSEP.getSelectedItem().toString())
                );
                break;
            default:
                noReg = query.cariIsiSmc(
                    "select lpad(ifnull(max(convert(no_reg, signed)), 0) + 1, 3, '0') from reg_periksa where kd_dokter = ? and kd_poli = ? and tgl_registrasi = ?",
                    kodeDokterRS, kodePoliRS, valid.SetTgl(tglSEP.getSelectedItem().toString())
                );
                break;
        }
        noRawat = query.cariIsiSmc(
            "select concat(date_format(tgl_registrasi, '%Y/%m/%d'), '/', lpad(ifnull(max(convert(right(no_rawat, 6), signed)), 0) + 1, 6, '0')) from reg_periksa where no_rawat = concat(date_format(?, '%Y/%m/%d'), '/%')",
            valid.SetTgl(tglSEP.getSelectedItem().toString())
        );
    }
    
    private void cekStatusPasien() {
        
    }
    
    private boolean simpanRegistrasi() {
        int coba = 0, maxCoba = 5;
        autonomor();
        boolean sukses = query.menyimpantfSmc("reg_periksa", null,
            noReg, noRawat, valid.setTglSmc(tglSEP), query.cariIsiSmc("select current_time()"), kodeDokterRS, noRM.getText(),
            kodePoliRS, namaPj, alamatPj, hubunganPj, biayaReg, "Belum", statusDaftar, "Ralan", "BPJ", umurDaftar, statusUmur,
            "Belum Bayar", statusPoli
        );
        
        while (coba < maxCoba && ! sukses) {
            autonomor();
            sukses = query.menyimpantfSmc("reg_periksa", null,
                noReg, noRawat, valid.setTglSmc(tglSEP), query.cariIsiSmc("select current_time()"), kodeDokterRS, noRM.getText(),
                kodePoliRS, namaPj, alamatPj, hubunganPj, biayaReg, "Belum", statusDaftar, "Ralan", "BPJ", umurDaftar, statusUmur,
                "Belum Bayar", statusPoli
            );
        }
        
        return sukses;
    }
    
    private void simpanDataPasien() {
        //
    }
    
    private void simpanAntrianOnsite() {
        //
    }

    private void simpanSEP() {
        //
    }
    
    private void printRegistrasi() {
        // 
    }

    private void updateSKDP() {
        //
    }

    private void resetInput() {
        noRM.setText("");
        namaPasien.setText("");
        tglLahir.setText("");
        statusPeserta.setText("");
        noSKDP.setText("");
        noRujukan.setText("");
        kodePPK.setText("");
        namaPPK.setText("");
        kodeDiagnosa.setText("");
        namaDiagnosa.setText("");
        kodePoli.setText("");
        namaPoli.setText("");
        kodeDokter.setText("");
        namaDokter.setText("");
        jenisPelayanan.setSelectedIndex(0);
        kelas.setSelectedIndex(2);
        tujuanKunjungan.setSelectedIndex(0);
        flagProsedur.setSelectedIndex(0);
        penunjang.setSelectedIndex(0);
        asesmenPelayanan.setSelectedIndex(0);
        kodeDPJPLayanan.setVisible(false);
        kodeDPJPLayanan.setText("");
        namaDPJPLayanan.setVisible(false);
        namaDPJPLayanan.setText("");
        LabelPoli8.setVisible(false);
        jenisPeserta.setText("");
        jk.setText("");
        nik.setText("");
        noKartu.setText("");
        asalRujukan.setSelectedIndex(0);
        tglSEP.setDate(new Date());
        tglRujuk.setDate(new Date());
        noTelp.setText("");
        katarak.setSelectedIndex(0);
        lakalantas.setSelectedIndex(0);
        tglKLL.setDate(new Date());
        keterangan.setText("");
        suplesi.setSelectedIndex(0);
        noSEPSuplesi.setText("");
        kodeProvKLL.setText("");
        namaProvKLL.setText("");
        kodeKabKLL.setText("");
        namaKabKLL.setText("");
        kodeKecKLL.setText("");
        namaKecKLL.setText("");
    }
}
