package khanzahmsanjungan;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class HalamanUtama extends javax.swing.JFrame {
    private final DlgAmbilAntrean ambilAntrian = new DlgAmbilAntrean(null, false);
    private final DlgCekNoRM daftarPoli = new DlgCekNoRM(null, false);
    private final DlgCekKunjunganPertamaSEP daftarSEPPertama = new DlgCekKunjunganPertamaSEP(null, false);
    private final DlgCekKunjunganBedaPoli daftarSEPBedaPoli = new DlgCekKunjunganBedaPoli(null, false);
    private final DlgCekSKDPKontrol daftarSEPKontrol = new DlgCekSKDPKontrol(null, false);
    private final DlgCekinMobileJKN daftarCekinMobileJKN = new DlgCekinMobileJKN(null, false);
    private final DlgPengaturanAPM pengaturanAPM = new DlgPengaturanAPM(null, false);
    
    public HalamanUtama() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize.width, screenSize.height);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIconImage(new ImageIcon(super.getClass().getResource("/picture/icon-48x48.png")).getImage());
        
        jPanel1.remove(menuAmbilAntrian);
        
        jPanel1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel39 = new widget.Label();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pengaturan = new widget.Button();
        PanelWall = new usu.widget.glass.PanelGlass();
        jPanel1 = new component.Panel();
        menuAmbilAntrian = new widget.ButtonBig();
        menuDaftarPoli = new widget.ButtonBig();
        menuDaftarSEPPertama = new widget.ButtonBig();
        menuDaftarSEPKontrol = new widget.ButtonBig();
        menuDaftarSEPBedaPoli = new widget.ButtonBig();
        menuCekinMobileJKN = new widget.ButtonBig();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ANJUNGAN PASIEN MANDIRI");
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBackground(new java.awt.Color(238, 238, 255));
        jPanel3.setForeground(new java.awt.Color(238, 238, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel39.setForeground(new java.awt.Color(0, 131, 62));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("ANJUNGAN PASIEN MANDIRI");
        jLabel39.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel39.setPreferredSize(new java.awt.Dimension(750, 75));
        jPanel3.add(jLabel39, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI SemiBold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Build 2024-03-14      ");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(238, 238, 255));
        jPanel2.setForeground(new java.awt.Color(238, 238, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/our_process_2.png"))); // NOI18N
        pengaturan.setGlassColor(new java.awt.Color(238, 238, 255));
        pengaturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengaturanActionPerformed(evt);
            }
        });
        jPanel2.add(pengaturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, -1, -1));

        PanelWall.setBackground(new java.awt.Color(238, 238, 255));
        PanelWall.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/icon-128x128.png"))); // NOI18N
        PanelWall.setForeground(new java.awt.Color(238, 238, 255));
        PanelWall.setPreferredSize(new java.awt.Dimension(150, 150));
        PanelWall.setRound(false);
        PanelWall.setWarna(new java.awt.Color(238, 238, 255));

        javax.swing.GroupLayout PanelWallLayout = new javax.swing.GroupLayout(PanelWall);
        PanelWall.setLayout(PanelWallLayout);
        PanelWallLayout.setHorizontalGroup(
            PanelWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        PanelWallLayout.setVerticalGroup(
            PanelWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel2.add(PanelWall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(238, 238, 255));
        jPanel1.setBorder(null);
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 1024));
        jPanel1.setLayout(new java.awt.GridLayout(0, 2));

        menuAmbilAntrian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/antrianpasien.png"))); // NOI18N
        menuAmbilAntrian.setText("AMBIL ANTRIAN");
        menuAmbilAntrian.setFont(new java.awt.Font("Inter Display", 1, 30)); // NOI18N
        menuAmbilAntrian.setIconTextGap(0);
        menuAmbilAntrian.setPreferredSize(new java.awt.Dimension(200, 90));
        menuAmbilAntrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAmbilAntrianActionPerformed(evt);
            }
        });
        jPanel1.add(menuAmbilAntrian);

        menuDaftarPoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/kioskselfservice.png"))); // NOI18N
        menuDaftarPoli.setText("DAFTAR POLIKLINIK");
        menuDaftarPoli.setFont(new java.awt.Font("Inter Display", 1, 30)); // NOI18N
        menuDaftarPoli.setIconTextGap(0);
        menuDaftarPoli.setPreferredSize(new java.awt.Dimension(200, 90));
        menuDaftarPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDaftarPoliActionPerformed(evt);
            }
        });
        jPanel1.add(menuDaftarPoli);

        menuDaftarSEPPertama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/48x48-bpjs.png"))); // NOI18N
        menuDaftarSEPPertama.setText("SEP KUNJUNGAN PERTAMA");
        menuDaftarSEPPertama.setFont(new java.awt.Font("Inter Display", 1, 30)); // NOI18N
        menuDaftarSEPPertama.setIconTextGap(0);
        menuDaftarSEPPertama.setPreferredSize(new java.awt.Dimension(200, 90));
        menuDaftarSEPPertama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDaftarSEPPertamaActionPerformed(evt);
            }
        });
        jPanel1.add(menuDaftarSEPPertama);

        menuDaftarSEPKontrol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/48x48-bpjs.png"))); // NOI18N
        menuDaftarSEPKontrol.setText("SEP KONTROL");
        menuDaftarSEPKontrol.setFont(new java.awt.Font("Inter Display", 1, 30)); // NOI18N
        menuDaftarSEPKontrol.setIconTextGap(0);
        menuDaftarSEPKontrol.setPreferredSize(new java.awt.Dimension(200, 90));
        menuDaftarSEPKontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDaftarSEPKontrolActionPerformed(evt);
            }
        });
        jPanel1.add(menuDaftarSEPKontrol);

        menuDaftarSEPBedaPoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/48x48-bpjs.png"))); // NOI18N
        menuDaftarSEPBedaPoli.setText("SEP KONTROL BEDA POLI");
        menuDaftarSEPBedaPoli.setFont(new java.awt.Font("Inter Display", 1, 30)); // NOI18N
        menuDaftarSEPBedaPoli.setIconTextGap(0);
        menuDaftarSEPBedaPoli.setPreferredSize(new java.awt.Dimension(200, 90));
        menuDaftarSEPBedaPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDaftarSEPBedaPoliActionPerformed(evt);
            }
        });
        jPanel1.add(menuDaftarSEPBedaPoli);

        menuCekinMobileJKN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/48x48-mjkn.png"))); // NOI18N
        menuCekinMobileJKN.setText("CEK IN MOBILEJKN");
        menuCekinMobileJKN.setFont(new java.awt.Font("Inter Display", 1, 30)); // NOI18N
        menuCekinMobileJKN.setIconTextGap(0);
        menuCekinMobileJKN.setPreferredSize(new java.awt.Dimension(200, 90));
        menuCekinMobileJKN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCekinMobileJKNActionPerformed(evt);
            }
        });
        jPanel1.add(menuCekinMobileJKN);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuDaftarSEPKontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDaftarSEPKontrolActionPerformed
        daftarSEPKontrol.clearText();
        daftarSEPKontrol.setSize(this.getWidth(), this.getHeight());
        daftarSEPKontrol.setLocationRelativeTo(this);
        daftarSEPKontrol.setVisible(true);
    }//GEN-LAST:event_menuDaftarSEPKontrolActionPerformed

    private void menuDaftarPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDaftarPoliActionPerformed
        daftarPoli.clearText();
        daftarPoli.setSize(this.getWidth(), this.getHeight());
        daftarPoli.setLocationRelativeTo(this);
        daftarPoli.setVisible(true);
    }//GEN-LAST:event_menuDaftarPoliActionPerformed

    private void menuDaftarSEPPertamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDaftarSEPPertamaActionPerformed
        daftarSEPPertama.clearText();
        daftarSEPPertama.setSize(this.getWidth(), this.getHeight());
        daftarSEPPertama.setLocationRelativeTo(this);
        daftarSEPPertama.setVisible(true);
    }//GEN-LAST:event_menuDaftarSEPPertamaActionPerformed

    private void menuCekinMobileJKNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCekinMobileJKNActionPerformed
        daftarCekinMobileJKN.clearText();
        daftarCekinMobileJKN.setSize(this.getWidth(), this.getHeight());
        daftarCekinMobileJKN.setLocationRelativeTo(this);
        daftarCekinMobileJKN.setVisible(true);
    }//GEN-LAST:event_menuCekinMobileJKNActionPerformed

    private void menuDaftarSEPBedaPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDaftarSEPBedaPoliActionPerformed
        daftarSEPBedaPoli.clearText();
        daftarSEPBedaPoli.setSize(this.getWidth(), this.getHeight());
        daftarSEPBedaPoli.setLocationRelativeTo(this);
        daftarSEPBedaPoli.setVisible(true);
    }//GEN-LAST:event_menuDaftarSEPBedaPoliActionPerformed

    private void menuAmbilAntrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAmbilAntrianActionPerformed
        ambilAntrian.setSize(this.getWidth(), this.getHeight());
        ambilAntrian.setLocationRelativeTo(this);
        ambilAntrian.setVisible(true);
    }//GEN-LAST:event_menuAmbilAntrianActionPerformed

    private void pengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengaturanActionPerformed
        pengaturanAPM.setSize(this.getWidth(), this.getHeight());
        pengaturanAPM.setLocationRelativeTo(this);
        pengaturanAPM.setVisible(true);
    }//GEN-LAST:event_pengaturanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.glass.PanelGlass PanelWall;
    private javax.swing.JLabel jLabel1;
    private widget.Label jLabel39;
    private component.Panel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private widget.ButtonBig menuAmbilAntrian;
    private widget.ButtonBig menuCekinMobileJKN;
    private widget.ButtonBig menuDaftarPoli;
    private widget.ButtonBig menuDaftarSEPBedaPoli;
    private widget.ButtonBig menuDaftarSEPKontrol;
    private widget.ButtonBig menuDaftarSEPPertama;
    private widget.Button pengaturan;
    // End of variables declaration//GEN-END:variables
}
