/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package khanzahmsanjungan;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author it-rsib
 */
public class HalamanUtama extends javax.swing.JFrame {
    public HalamanUtama() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize.width, screenSize.height);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIconImage(new ImageIcon(super.getClass().getResource("/picture/icon-48x48.png")).getImage());
        
        jPanel1.remove(ambilAntrian);
        jPanel1.remove(btnAdmin11);
        jPanel1.remove(cekInRegistrasi);
        
        jPanel1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel39 = new widget.Label();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PanelWall = new usu.widget.glass.PanelGlass();
        jPanel1 = new component.Panel();
        ambilAntrian = new widget.ButtonBig();
        cekInRegistrasi = new widget.ButtonBig();
        daftarPoliJaminanPribadi = new widget.ButtonBig();
        daftarBPJSKunjunganPertama = new widget.ButtonBig();
        daftarBPJSKontrol = new widget.ButtonBig();
        daftarBPJSKontrolBedaPoli = new widget.ButtonBig();
        cekInMobileJKN = new widget.ButtonBig();
        btnAdmin11 = new widget.ButtonBig();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ANJUNGAN PASIEN MANDIRI");
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBackground(new java.awt.Color(238, 238, 255));
        jPanel3.setForeground(new java.awt.Color(238, 238, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel39.setForeground(new java.awt.Color(0, 131, 62));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("ANJUNGAN PASIEN MANDIRI");
        jLabel39.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel39.setPreferredSize(new java.awt.Dimension(750, 75));
        jPanel3.add(jLabel39, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI SemiBold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Build 2024-03-14      ");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(238, 238, 255));
        jPanel2.setForeground(new java.awt.Color(238, 238, 255));

        PanelWall.setBackground(new java.awt.Color(238, 238, 255));
        PanelWall.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/icon-128x128.png"))); // NOI18N
        PanelWall.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        PanelWall.setForeground(new java.awt.Color(238, 238, 255));
        PanelWall.setPreferredSize(new java.awt.Dimension(150, 150));
        PanelWall.setRound(false);
        PanelWall.setWarna(new java.awt.Color(238, 238, 255));

        javax.swing.GroupLayout PanelWallLayout = new javax.swing.GroupLayout(PanelWall);
        PanelWall.setLayout(PanelWallLayout);
        PanelWallLayout.setHorizontalGroup(
            PanelWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        PanelWallLayout.setVerticalGroup(
            PanelWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel2.add(PanelWall);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(238, 238, 255));
        jPanel1.setBorder(null);
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 1024));
        jPanel1.setLayout(new java.awt.GridLayout(0, 2));

        ambilAntrian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/antrianpasien.png"))); // NOI18N
        ambilAntrian.setText("AMBIL ANTRIAN");
        ambilAntrian.setFont(new java.awt.Font("Inter Display", 1, 30)); // NOI18N
        ambilAntrian.setIconTextGap(0);
        ambilAntrian.setPreferredSize(new java.awt.Dimension(200, 90));
        ambilAntrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambilAntrianActionPerformed(evt);
            }
        });
        jPanel1.add(ambilAntrian);

        cekInRegistrasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/checkin.png"))); // NOI18N
        cekInRegistrasi.setText("CEK IN REGISTRASI");
        cekInRegistrasi.setEnabled(false);
        cekInRegistrasi.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        cekInRegistrasi.setIconTextGap(0);
        cekInRegistrasi.setPreferredSize(new java.awt.Dimension(200, 90));
        cekInRegistrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekInRegistrasiActionPerformed(evt);
            }
        });
        jPanel1.add(cekInRegistrasi);

        daftarPoliJaminanPribadi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/kioskselfservice.png"))); // NOI18N
        daftarPoliJaminanPribadi.setText("DAFTAR POLIKLINIK");
        daftarPoliJaminanPribadi.setFont(new java.awt.Font("Inter Display", 1, 30)); // NOI18N
        daftarPoliJaminanPribadi.setIconTextGap(0);
        daftarPoliJaminanPribadi.setPreferredSize(new java.awt.Dimension(200, 90));
        daftarPoliJaminanPribadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarPoliJaminanPribadiActionPerformed(evt);
            }
        });
        jPanel1.add(daftarPoliJaminanPribadi);

        daftarBPJSKunjunganPertama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/48x48-bpjs.png"))); // NOI18N
        daftarBPJSKunjunganPertama.setText("SEP KUNJUNGAN PERTAMA");
        daftarBPJSKunjunganPertama.setFont(new java.awt.Font("Inter Display", 1, 30)); // NOI18N
        daftarBPJSKunjunganPertama.setIconTextGap(0);
        daftarBPJSKunjunganPertama.setPreferredSize(new java.awt.Dimension(200, 90));
        daftarBPJSKunjunganPertama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarBPJSKunjunganPertamaActionPerformed(evt);
            }
        });
        jPanel1.add(daftarBPJSKunjunganPertama);

        daftarBPJSKontrol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/48x48-bpjs.png"))); // NOI18N
        daftarBPJSKontrol.setText("SEP KONTROL");
        daftarBPJSKontrol.setFont(new java.awt.Font("Inter Display", 1, 30)); // NOI18N
        daftarBPJSKontrol.setIconTextGap(0);
        daftarBPJSKontrol.setPreferredSize(new java.awt.Dimension(200, 90));
        daftarBPJSKontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarBPJSKontrolActionPerformed(evt);
            }
        });
        jPanel1.add(daftarBPJSKontrol);

        daftarBPJSKontrolBedaPoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/48x48-bpjs.png"))); // NOI18N
        daftarBPJSKontrolBedaPoli.setText("SEP KONTROL BEDA POLI");
        daftarBPJSKontrolBedaPoli.setFont(new java.awt.Font("Inter Display", 1, 30)); // NOI18N
        daftarBPJSKontrolBedaPoli.setIconTextGap(0);
        daftarBPJSKontrolBedaPoli.setPreferredSize(new java.awt.Dimension(200, 90));
        daftarBPJSKontrolBedaPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarBPJSKontrolBedaPoliActionPerformed(evt);
            }
        });
        jPanel1.add(daftarBPJSKontrolBedaPoli);

        cekInMobileJKN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/48x48-mjkn.png"))); // NOI18N
        cekInMobileJKN.setText("CEK IN MOBILEJKN");
        cekInMobileJKN.setFont(new java.awt.Font("Inter Display", 1, 30)); // NOI18N
        cekInMobileJKN.setIconTextGap(0);
        cekInMobileJKN.setPreferredSize(new java.awt.Dimension(200, 90));
        cekInMobileJKN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekInMobileJKNActionPerformed(evt);
            }
        });
        jPanel1.add(cekInMobileJKN);

        btnAdmin11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/logo-satset.png"))); // NOI18N
        btnAdmin11.setText("AKTIVASI SATUSEHAT");
        btnAdmin11.setEnabled(false);
        btnAdmin11.setFont(new java.awt.Font("Inter", 1, 30)); // NOI18N
        btnAdmin11.setIconTextGap(0);
        btnAdmin11.setPreferredSize(new java.awt.Dimension(200, 90));
        btnAdmin11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmin11ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmin11);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void daftarBPJSKontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarBPJSKontrolActionPerformed
        DlgCekSKDPKontrol pilih = new DlgCekSKDPKontrol(null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_daftarBPJSKontrolActionPerformed

    private void daftarPoliJaminanPribadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarPoliJaminanPribadiActionPerformed
        DlgCekNoRM pilih = new DlgCekNoRM(null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_daftarPoliJaminanPribadiActionPerformed

    private void cekInRegistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekInRegistrasiActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Mohon maaf, fitur masih dalam tahap pengembangan");
//        DlgCekBooking pilih = new DlgCekBooking(null, true);
//        pilih.setSize(this.getWidth(), this.getHeight());
//        pilih.setLocationRelativeTo(this);
//        pilih.setVisible(true);
    }//GEN-LAST:event_cekInRegistrasiActionPerformed

    private void daftarBPJSKunjunganPertamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarBPJSKunjunganPertamaActionPerformed
        DlgCekKunjunganPertamaSEP pilih = new DlgCekKunjunganPertamaSEP(null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_daftarBPJSKunjunganPertamaActionPerformed

    private void cekInMobileJKNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekInMobileJKNActionPerformed
        DlgCekinMobileJKN pilih = new DlgCekinMobileJKN(null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);

//        JOptionPane.showMessageDialog(rootPane, "Mohon maaf, fitur masih dalam tahap pengembangan");
    }//GEN-LAST:event_cekInMobileJKNActionPerformed

    private void daftarBPJSKontrolBedaPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarBPJSKontrolBedaPoliActionPerformed
        DlgCekKunjunganBedaPoli pilih = new DlgCekKunjunganBedaPoli(null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_daftarBPJSKontrolBedaPoliActionPerformed

    private void ambilAntrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambilAntrianActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Mohon maaf, fitur masih dalam tahap pengembangan");
//        HalamanUtamaAntrian pilih = new HalamanUtamaAntrian();
//        pilih.setSize(this.getWidth(), this.getHeight());
//        pilih.setLocationRelativeTo(this);
//        pilih.setVisible(true);
    }//GEN-LAST:event_ambilAntrianActionPerformed

    private void btnAdmin11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmin11ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Mohon maaf, fitur masih dalam tahap pengembangan");
//        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
//        String nikktppetugas = Sequel.cariIsi("select no_ktp from pegawai where nik='0132' ");
//        Valid.panggilUrl("kyc/index.php?&nikagent=" + nikktppetugas + "");
//        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_btnAdmin11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.glass.PanelGlass PanelWall;
    private widget.ButtonBig ambilAntrian;
    private widget.ButtonBig btnAdmin11;
    private widget.ButtonBig cekInMobileJKN;
    private widget.ButtonBig cekInRegistrasi;
    private widget.ButtonBig daftarBPJSKontrol;
    private widget.ButtonBig daftarBPJSKontrolBedaPoli;
    private widget.ButtonBig daftarBPJSKunjunganPertama;
    private widget.ButtonBig daftarPoliJaminanPribadi;
    private javax.swing.JLabel jLabel1;
    private widget.Label jLabel39;
    private component.Panel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
